language: rust
rust:
- nightly
- beta
sudo: false
before_script:
- pip install git+https://github.com/jansegre/travis-cargo.git --user $USER && export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo cargo build
- travis-cargo cargo test
- travis-cargo cargo doc
after_success:
- travis-cargo --only beta doc-upload
env:
  global:
    secure: ZDFBTFXJEvngxy26NMSgoD3A+OSp9OD4l0KrSIwoCbo8Qyk5rpLf6kc7gbEgK2pgW3e77VrjiSeTGYhcx+Sm2x/ZOHfSYIwcaT9siBmkSs8p21vz7L3boaf3UzOR09ebACoN9aUhZl3nNFw/eI82c+KEKcjMbN3Rb9z91LIJ47A=
